//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CADOfficeProjT
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public int Month { get; set; }
        public string UserName { get; set; }
        public string Customer { get; set; }
        public string CustomerOrderNo { get; set; }
        public string MatrixSalesOrderNo { get; set; }
        public string CustomerProjectCode { get; set; }
        public string MatrixProjectCode { get; set; }
        public string COPTNumber { get; set; }
        public Nullable<int> COPT_Project { get; set; }
        public int Year { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
