//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientStaffMember
    {
        public ClientStaffMember()
        {
            this.ClientStaffMemberMITPSignatories = new HashSet<ClientStaffMemberMITPSignatory>();
            this.ClientStaffMemberProjects = new HashSet<ClientStaffMemberProject>();
            this.ClientStaffMemberReviewers = new HashSet<ClientStaffMemberReviewer>();
            this.ClientStaffMemberRFIRecipients = new HashSet<ClientStaffMemberRFIRecipient>();
            this.ClientStaffMemberRFIRespondents = new HashSet<ClientStaffMemberRFIRespondent>();
            this.ClientStaffMemberValidationAttendees = new HashSet<ClientStaffMemberValidationAttendee>();
            this.ClientStaffMemberVerificationAttendees = new HashSet<ClientStaffMemberVerificationAttendee>();
            this.Transmittals = new HashSet<Transmittal>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> ClientStaffMember_Customer { get; set; }
    
        public virtual ICollection<ClientStaffMemberMITPSignatory> ClientStaffMemberMITPSignatories { get; set; }
        public virtual ICollection<ClientStaffMemberProject> ClientStaffMemberProjects { get; set; }
        public virtual ICollection<ClientStaffMemberReviewer> ClientStaffMemberReviewers { get; set; }
        public virtual ICollection<ClientStaffMemberRFIRecipient> ClientStaffMemberRFIRecipients { get; set; }
        public virtual ICollection<ClientStaffMemberRFIRespondent> ClientStaffMemberRFIRespondents { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<ClientStaffMemberValidationAttendee> ClientStaffMemberValidationAttendees { get; set; }
        public virtual ICollection<ClientStaffMemberVerificationAttendee> ClientStaffMemberVerificationAttendees { get; set; }
        public virtual ICollection<Transmittal> Transmittals { get; set; }
    }
}
