//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CofC
    {
        public CofC()
        {
            this.CofCDocs = new HashSet<CofCDoc>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string CustomerProjectCode { get; set; }
        public string Customer { get; set; }
        public string CustomerOrderNo { get; set; }
        public string MatrixSalesOrderNo { get; set; }
        public string UserName { get; set; }
        public string CofCDate { get; set; }
        public string CertificateNo { get; set; }
        public string DeliveryNoteNo { get; set; }
        public Nullable<int> CofC_Project { get; set; }
    
        public virtual ICollection<CofCDoc> CofCDocs { get; set; }
        public virtual Project Project { get; set; }
    }
}
