//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.ClientStaffMembers = new HashSet<ClientStaffMember>();
            this.Projects = new HashSet<Project>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string CustomerName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public string PostCode { get; set; }
    
        public virtual ICollection<ClientStaffMember> ClientStaffMembers { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
