//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DandDA
    {
        public DandDA()
        {
            this.DandADocs = new HashSet<DandADoc>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string CustomerProjectCode { get; set; }
        public string Customer { get; set; }
        public string CustomerOrderNo { get; set; }
        public string MatrixSalesOrderNo { get; set; }
        public string ProjectTitle { get; set; }
        public string UserName { get; set; }
        public string UserPosition { get; set; }
        public string DDADate { get; set; }
        public string MatrixProjectCode { get; set; }
        public string DDANumber { get; set; }
        public int DandDA_Project { get; set; }
    
        public virtual ICollection<DandADoc> DandADocs { get; set; }
        public virtual Project Project { get; set; }
    }
}
