//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DandDC
    {
        public DandDC()
        {
            this.ClientStaffMemberValidationAttendees = new HashSet<ClientStaffMemberValidationAttendee>();
            this.ClientStaffMemberVerificationAttendees = new HashSet<ClientStaffMemberVerificationAttendee>();
            this.MatrixStaffMemberValidationAttendees = new HashSet<MatrixStaffMemberValidationAttendee>();
            this.MatrixStaffMemberVerificationAttendees = new HashSet<MatrixStaffMemberVerificationAttendee>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string ProjectTitle { get; set; }
        public string CustomerProjectCode { get; set; }
        public string Customer { get; set; }
        public string CustomerOrderNo { get; set; }
        public string MatrixProjectCode { get; set; }
        public string MatrixSalesOrderNo { get; set; }
        public string UserName { get; set; }
        public string BasedOn { get; set; }
        public string Essentials { get; set; }
        public string StatsRegs { get; set; }
        public string SpecReqs { get; set; }
        public string OutputsVerification { get; set; }
        public Nullable<System.DateTime> OutputsVeriMDate { get; set; }
        public string OutputsValidation { get; set; }
        public Nullable<System.DateTime> OutputsValiMDate { get; set; }
        public Nullable<bool> ProtoTypeProduced { get; set; }
        public Nullable<bool> MaterialsCosted { get; set; }
        public Nullable<bool> LabourCosted { get; set; }
        public Nullable<bool> ClientApproved { get; set; }
        public string DandDCStartDate { get; set; }
        public string UserPosition { get; set; }
        public string DDCNumber { get; set; }
        public string ClientVerificationMeetingAttendees { get; set; }
        public string MatrixVerificationMeetingAttendees { get; set; }
        public string ClientValidationMeetingAttendees { get; set; }
        public string MatrixValidationMeetingAttendees { get; set; }
    
        public virtual ICollection<ClientStaffMemberValidationAttendee> ClientStaffMemberValidationAttendees { get; set; }
        public virtual ICollection<ClientStaffMemberVerificationAttendee> ClientStaffMemberVerificationAttendees { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<MatrixStaffMemberValidationAttendee> MatrixStaffMemberValidationAttendees { get; set; }
        public virtual ICollection<MatrixStaffMemberVerificationAttendee> MatrixStaffMemberVerificationAttendees { get; set; }
    }
}
