//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drawing
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string DrawingNumber { get; set; }
        public string DrawingRevision { get; set; }
        public string DrawingTitle { get; set; }
        public string DrawingStatus { get; set; }
        public string VaultLocation { get; set; }
        public string VaultStatus { get; set; }
        public string DrawingPrefixStr { get; set; }
        public int Drawing_Project { get; set; }
        public int DrawingPrefix_Drawing { get; set; }
    
        public virtual DrawingPrefix DrawingPrefix { get; set; }
        public virtual Project Project { get; set; }
    }
}
