//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawingPrefix
    {
        public DrawingPrefix()
        {
            this.Drawings = new HashSet<Drawing>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string Prefix { get; set; }
    
        public virtual ICollection<Drawing> Drawings { get; set; }
    }
}
