//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixStaffMemberMITPSignatory
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public int MatrixStaffMemberMITPSignatory_MITP { get; set; }
        public int MatrixStaffMemberMITPSignatory_MatrixStaffMember { get; set; }
    
        public virtual MatrixStaffMember MatrixStaffMember { get; set; }
        public virtual MITPDetail MITPDetail { get; set; }
    }
}
