//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixStaffMember
    {
        public MatrixStaffMember()
        {
            this.MatrixStaffMemberMITPSignatories = new HashSet<MatrixStaffMemberMITPSignatory>();
            this.MatrixStaffMemberProjects = new HashSet<MatrixStaffMemberProject>();
            this.MatrixStaffMemberReviewers = new HashSet<MatrixStaffMemberReviewer>();
            this.MatrixStaffMemberRFIRespondents = new HashSet<MatrixStaffMemberRFIRespondent>();
            this.MatrixStaffMemberValidationAttendees = new HashSet<MatrixStaffMemberValidationAttendee>();
            this.MatrixStaffMemberVerificationAttendees = new HashSet<MatrixStaffMemberVerificationAttendee>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<MatrixStaffMemberMITPSignatory> MatrixStaffMemberMITPSignatories { get; set; }
        public virtual ICollection<MatrixStaffMemberProject> MatrixStaffMemberProjects { get; set; }
        public virtual ICollection<MatrixStaffMemberReviewer> MatrixStaffMemberReviewers { get; set; }
        public virtual ICollection<MatrixStaffMemberRFIRespondent> MatrixStaffMemberRFIRespondents { get; set; }
        public virtual ICollection<MatrixStaffMemberValidationAttendee> MatrixStaffMemberValidationAttendees { get; set; }
        public virtual ICollection<MatrixStaffMemberVerificationAttendee> MatrixStaffMemberVerificationAttendees { get; set; }
    }
}
