//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MITP
    {
        public MITP()
        {
            this.MITPDetails = new HashSet<MITPDetail>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string MITPNumber { get; set; }
        public System.DateTime MITPRevStart { get; set; }
        public Nullable<System.DateTime> MITPRevEnd { get; set; }
        public int MITPRevNumber { get; set; }
        public bool MITPRevCurrent { get; set; }
    
        public virtual ICollection<MITPDetail> MITPDetails { get; set; }
    }
}
