//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MITPDetail
    {
        public MITPDetail()
        {
            this.ClientStaffMemberMITPSignatories = new HashSet<ClientStaffMemberMITPSignatory>();
            this.MatrixStaffMemberMITPSignatories = new HashSet<MatrixStaffMemberMITPSignatory>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string CustomerProjectCode { get; set; }
        public string Customer { get; set; }
        public string MatrixProjectCode { get; set; }
        public string MatrixSalesOrderNo { get; set; }
        public string MERDocumentNumber { get; set; }
        public Nullable<int> MITP_Project { get; set; }
        public int MITPDetail_MITP { get; set; }
    
        public virtual ICollection<ClientStaffMemberMITPSignatory> ClientStaffMemberMITPSignatories { get; set; }
        public virtual ICollection<MatrixStaffMemberMITPSignatory> MatrixStaffMemberMITPSignatories { get; set; }
        public virtual MITP MITP { get; set; }
        public virtual Project Project { get; set; }
    }
}
