//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.CADOfficeProjTS = new HashSet<CADOfficeProjT>();
            this.ClientStaffMemberProjects = new HashSet<ClientStaffMemberProject>();
            this.CofCs = new HashSet<CofC>();
            this.DandDAs = new HashSet<DandDA>();
            this.Drawings = new HashSet<Drawing>();
            this.MatrixStaffMemberProjects = new HashSet<MatrixStaffMemberProject>();
            this.MITPDetails = new HashSet<MITPDetail>();
            this.Tasks = new HashSet<Task>();
            this.Reviews = new HashSet<Review>();
            this.RFIs = new HashSet<RFI>();
            this.TQDetails = new HashSet<TQDetail>();
            this.Transmittals = new HashSet<Transmittal>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string ProjectTitle { get; set; }
        public string CustomerProjectCode { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string MatrixProjectCode { get; set; }
        public string MatrixSalesOrderNumber { get; set; }
        public string Notes { get; set; }
        public int Project_Customer { get; set; }
    
        public virtual ICollection<CADOfficeProjT> CADOfficeProjTS { get; set; }
        public virtual ICollection<ClientStaffMemberProject> ClientStaffMemberProjects { get; set; }
        public virtual ICollection<CofC> CofCs { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<DandDA> DandDAs { get; set; }
        public virtual DandDC DandDC { get; set; }
        public virtual DrawingRegister DrawingRegister { get; set; }
        public virtual ICollection<Drawing> Drawings { get; set; }
        public virtual ICollection<MatrixStaffMemberProject> MatrixStaffMemberProjects { get; set; }
        public virtual ICollection<MITPDetail> MITPDetails { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<RFI> RFIs { get; set; }
        public virtual ICollection<TQDetail> TQDetails { get; set; }
        public virtual ICollection<Transmittal> Transmittals { get; set; }
    }
}
