//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.ClientStaffMemberReviewers = new HashSet<ClientStaffMemberReviewer>();
            this.MatrixStaffMemberReviewers = new HashSet<MatrixStaffMemberReviewer>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public string ReviewLocation { get; set; }
        public string ReviewComment { get; set; }
        public string ReviewDateStr { get; set; }
        public string ReviewNumber { get; set; }
        public string Reviewer { get; set; }
        public int Review_Project { get; set; }
    
        public virtual ICollection<ClientStaffMemberReviewer> ClientStaffMemberReviewers { get; set; }
        public virtual ICollection<MatrixStaffMemberReviewer> MatrixStaffMemberReviewers { get; set; }
        public virtual Project Project { get; set; }
    }
}
