//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFI
    {
        public RFI()
        {
            this.ClientStaffMemberRFIRecipients = new HashSet<ClientStaffMemberRFIRecipient>();
            this.ClientStaffMemberRFIRespondents = new HashSet<ClientStaffMemberRFIRespondent>();
            this.MatrixStaffMemberRFIRespondents = new HashSet<MatrixStaffMemberRFIRespondent>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string RFINumber { get; set; }
        public string ProjectTitle { get; set; }
        public string CustomerProjectCode { get; set; }
        public string Customer { get; set; }
        public string CustomerOrderNo { get; set; }
        public string MatrixSalesOrderNo { get; set; }
        public string MatrixProjectCode { get; set; }
        public string UserName { get; set; }
        public string UserPosition { get; set; }
        public string DrawingNumber { get; set; }
        public string DrawingRevision { get; set; }
        public string RFIDate { get; set; }
        public string RFIRecipient { get; set; }
        public string RequestText { get; set; }
        public string ResponseToRFI { get; set; }
        public string RespondentPosition { get; set; }
        public string ResponseDate { get; set; }
        public string ResponseImplications { get; set; }
        public string Respondent { get; set; }
        public string MatrixRespondent { get; set; }
        public string MatrixRespondentPosition { get; set; }
        public string MatrixRespondentDate { get; set; }
        public Nullable<int> RFI_Project { get; set; }
    
        public virtual ICollection<ClientStaffMemberRFIRecipient> ClientStaffMemberRFIRecipients { get; set; }
        public virtual ICollection<ClientStaffMemberRFIRespondent> ClientStaffMemberRFIRespondents { get; set; }
        public virtual ICollection<MatrixStaffMemberRFIRespondent> MatrixStaffMemberRFIRespondents { get; set; }
        public virtual Project Project { get; set; }
    }
}
