//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public System.DateTime Day { get; set; }
        public string TaskName { get; set; }
        public string Hours { get; set; }
        public string TaskDate { get; set; }
        public int TaskType_Task { get; set; }
        public Nullable<int> Task_Project { get; set; }
        public string User { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual TaskType TaskType { get; set; }
    }
}
