//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transmittal
    {
        public Transmittal()
        {
            this.TransmittalDocs = new HashSet<TransmittalDoc>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string ProjectTitle { get; set; }
        public string CustomerProjectCode { get; set; }
        public string Customer { get; set; }
        public string CustomerOrderNo { get; set; }
        public string MatrixSalesOrderNo { get; set; }
        public string UserName { get; set; }
        public System.DateTime Month { get; set; }
        public string QueryDate { get; set; }
        public string TransmittalNumber { get; set; }
        public int Transmittal_Project { get; set; }
        public int Transmittal_Recipient { get; set; }
        public string MatrixProjectCode { get; set; }
        public Nullable<int> Transmittal_TransmittalDoc { get; set; }
    
        public virtual ClientStaffMember ClientStaffMember { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<TransmittalDoc> TransmittalDocs { get; set; }
    }
}
