//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransmittalDoc
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string DocNo { get; set; }
        public string DocRevision { get; set; }
        public string SheetSize { get; set; }
        public string MPENumber { get; set; }
        public string DocTitle { get; set; }
        public string Copies { get; set; }
        public int TransmittalDoc_Transmittal { get; set; }
        public Nullable<int> TransmittalDoc_Reason { get; set; }
    
        public virtual TransmittalDocReasonsForIssue TransmittalDocReasonsForIssue { get; set; }
        public virtual Transmittal Transmittal { get; set; }
    }
}
